export const sample_foods = [
  {
    id: '1',
    name: '4 cheese Pizza',
    cookTime: '10-20',
    price: 35,
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'pizza/cheese_pizza.jpg',
    tags: ['FastFood', 'Pizza'],
  },
  {
    id: '2',
    name: 'Fried Chicken',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['USA'],
    stars: 4,
    imageUrl: 'salad/fried_chicken.jpg',
    tags: ['FastFood', 'Chicken'],
  },
  {
    id: '3',
    name: 'Mozzarella Cheese Salad',
    price: 10,
    cookTime: '10-15',
    favorite: false,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'salad/cheese_salad.jpg',
    tags: ['Cheese', 'Salad'],
  },
  {
    id: '4',
    name: 'Cheese Fruit Salad',
    price: 15,
    cookTime: '15-20',
    favorite: true,
    origins: ['Italy'],
    stars: 4.5,
    imageUrl: 'salad/fruit_salad.jpg',
    tags: ['Cheese', 'Salad', 'Fruit'],
  },
  {
    id: '5',
    name: 'Chocolate Ice Cream',
    price: 9,
    cookTime: '15-15',
    favorite: false,
    origins: ['French'],
    stars: 4.5,
    imageUrl: 'desserts/chocolate_cream.jpg', // Ensure this path is correct
    tags: ['Dessert', 'Ice Cream'],
  },
  {
    id: '6',
    name: 'Tiramisu',
    price: 9,
    cookTime: '20-30',
    favorite: false,
    origins: ['Italy'],
    stars: 4.0,
    imageUrl: 'desserts/tiramisu.jpg',
    tags: ['Dessert', 'Cake'],
  },
  {
    id: '7',
    name: 'Orange Juice',
    price: 5,
    cookTime: '5-10',
    favorite: false,
    origins: ['Asia'],
    stars: 4.0,
    imageUrl: 'drink/nuoc_cam.jpg',
    tags: ['Drink', 'Juice'],
  },
  {
    id: '8',
    name: 'Beer',
    price: 7,
    cookTime: '5-10',
    favorite: false,
    origins: ['Asia'],
    stars: 4.0,
    imageUrl: 'drink/bia.jpg',
    tags: ['Drink'],
  },
  {
    id: '9',
    name: 'Carbonara Pasta',
    price: 25,
    cookTime: '20-30',
    favorite: true,
    origins: ['Italy'],
    stars: 5.0,
    imageUrl: 'pasta/cabonara_pasta.jpg',
    tags: ['Pasta'],
  },
  {
    id: '10',
    name: 'Cheese Crab Pasta',
    price: 30,
    cookTime: '20-30',
    favorite: true,
    origins: ['Italy'],
    stars: 5.0,
    imageUrl: 'pasta/crab_pasta.jpg',
    tags: ['Pasta'],
  },
  {
    id: '11',
    name: 'Steak and Fries',
    price: 40,
    cookTime: '20-30',
    favorite: true,
    origins: ['USA'],
    stars: 5.0,
    imageUrl: 'pasta/steak.jpg',
    tags: ['Steak'],
  },
];

export const sample_users = [
{
  id: 1,
  name: 'John Doe',
  email: 'john@gmail.com',
  password: '12345',
  address: 'Toronto On',
  isAdmin: false,
},
{
  id: 2,
  name: 'Jane Doe',
  email: 'jane@gmail.com',
  password: '12345',
  address: 'Shanghai',
  isAdmin: true,
},
];